version: "3.8"
services:
  api:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /app
    command: npm run start:dev

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
      - db-nest:/var/lib/mysql
    environment:
      MYSQL_DATABASE: develop
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    container_name: mysql

  redis:
    image: redis:5.0.5-alpine
    container_name: redis
    ports:
    - "6379:6379"

volumes:
    db-nest:
